# Generated by Django 4.2.30 on 2026-05-21 06:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminBillInventory",
            fields=[
                ("sl_no", models.AutoField(primary_key=True, serialize=False)),
                ("vendor_bill_no", models.CharField(max_length=100)),
                ("vendor_bill_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Auto-calculated total sum of all items",
                        max_digits=12,
                    ),
                ),
                (
                    "div_section",
                    models.CharField(help_text="Division or Section", max_length=100),
                ),
                (
                    "indent_end_user",
                    models.CharField(help_text="Indent End User", max_length=100),
                ),
                ("received_date", models.DateField()),
                ("bill_received_date", models.DateField()),
                ("processed_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique Employee ID",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile", models.CharField(max_length=15)),
                ("designation", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user", models.CharField(default="System", max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("record_id", models.CharField(max_length=100)),
                ("record_name", models.CharField(max_length=255)),
                (
                    "changed_fields",
                    models.TextField(blank=True, help_text="JSON list of changes"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=150, unique=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=50)),
                ("branch", models.CharField(max_length=100)),
                ("ifsc_code", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ItemManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "gst",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        help_text="GST percentage",
                        max_digits=5,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "issue_status",
                    models.CharField(
                        choices=[("IN_STOCK", "In Stock"), ("ISSUED", "Issued")],
                        default="IN_STOCK",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.adminbillinventory",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_items",
                        to="core.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adminbillinventory",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="core.vendorbankaccount",
            ),
        ),
    ]
